open! Core
include Cint0

let dtype ~bits =
  Dtype.Wrap.create ~equal ~sexp_of_t
    ~max_layout_of:(fun v -> Bits_fixed (bitwidth v))
    ~cint_of:(fun v -> v)
    ~of_cint:(fun v -> Some v)
    ~layout:(Bits_fixed bits)

let dtype_8 = dtype ~bits:8
let dtype_16 = dtype ~bits:16
let dtype_32 = dtype ~bits:32
let dtype_64 = dtype ~bits:64

(* basically all of the rest of this should be able to be autogenerated *)

module E = struct
  type t = Cint0.t Expr.Wrap.t

  include Expr.CInt_

  let bit_not _ ~bits:_ = failwith "TODO"
  let bit_at _ ~bit:_ = failwith "TODO"
  let bit_slice _ ~lower_inc:_ ~upper_inc:_ = failwith "TODO"
  let mul_wrap _ _ ~bits:_ = failwith "TODO"
  let pow _ _ = failwith "TODO"
  let of_bool v = Cbool.E.to_int v
  let lt _ = failwith "TODO"
  let gt _ = failwith "TODO"
  let le _ = failwith "TODO"
  let ge _ = failwith "TODO"
  let is_zero _ = failwith "TODO"
  let is_nonzero _ = failwith "TODO"
  let assert_fits _ ~bits:_ = failwith "TODO"
  let concat2 _ _ = failwith "TODO"
  let concat _ = failwith "TODO"
  let zero = cint 0
  let one = cint 1
  let two = cint 2
  let three = cint 3
  let four = cint 4
  let five = cint 5
end

let apply_overflow dtype expr ~overflow =
  match overflow with
  | Overflow_behavior.Cant -> expr
  | Mask ->
      let bits = match Dtype.Ir.layout dtype with Bits_fixed width -> width in
      let mask = Cint0.(pow (of_int 2) (of_int bits) - of_int 1) in
      E.(bit_and expr (const mask))

module N = struct
  type t = Node.Wrap.t

  let assign ?loc var expr ~overflow =
    let var = Var.Ir.unwrap var in
    let expr = apply_overflow var.u.d.dtype expr ~overflow |> Expr.Ir.unwrap in
    Node.Ir.No_width_checks.assign ?loc var expr

  let incr ?loc var_id ~overflow =
    let expr = E.(var var_id |> add (cint 1)) in
    assign ?loc var_id expr ~overflow

  let decr ?loc var_id ~underflow =
    let expr = E.(sub (var var_id) (cint 1)) in
    assign ?loc var_id expr ~overflow:underflow

  let send ?loc chan_id expr ~overflow =
    let chan_id = Chan.Ir.unwrap_w chan_id in
    let expr =
      apply_overflow chan_id.d.dtype expr ~overflow |> Expr.Ir.unwrap
    in
    Node.Ir.No_width_checks.send ?loc chan_id expr

  let send' ?loc chan_id var_id ~overflow =
    send ?loc chan_id Expr.Wrap.(var var_id) ~overflow
end
